### PR TITLE
set automatic_options to True as specified in decorator.cross_origin docstring

### PR DESCRIPTION
**Pull request by fpischedda**
automatic_options set to True is very useful is many cases

### CODE REVIEW

**Comment by ashleysommer** [comment]
Thanks for the PR.

The default value of `automatic_options` as written in the docstring is actually left-over from when the plugin was ported from the Flask-CORS codebase. It should not be relied to to be accurate, and I will change the docstrings in a future release.

Which value `automatic_options` should default to is something I've been thinking about for a while.

I agree setting `automatic_options` `True` is useful in many cases.
I also recognise that having it default to `False` breaks the consistency with Flask-CORS because Flask-CORS has `automatic_options` set to `True` as default behaviour, and Flask-CORS documentation is written with the assumption that `automatic_options` is turned on.

However I feel that leaving `automatic_options` default to `False` in Sanic-CORS is more consistent with the Sanic design mentality. Sanic strives to be as fast as possible out of the box. I believe Sanic plugins also need to be written to be as fast as possible with their default options.

Due to the architecture of the Sanic internal request handler, setting `automatic_options` in Sanic-CORS requires the plugin to register a request middleware function. All extra middleware functions add to the overall response time of every request. If `automatic_options` is left in its default `False` setting, then this extra request middleware is not registered.

Another argument against `automatic_options` is to look at the default accepted HTTP methods on every Sanic route. By default only `GET` is allowed, and this is 'feature' documented in the Sanic docs and well-known by Sanic users. By setting `automatic_options` to True in Sanic-CORS, this implicitly allows `OPTIONS` requests to also be accepted. If `automatic_options` is set to True in Sanic-CORS, this inconsistency with Sanic routes could cause confusion with new users. By having `automatic_options` default to `False`, the user is choosing to 'opt-out' of the default behaviour by setting it to `True`, they are indicating that they want to change the way Sanic usually works.

For these two reasons, I will keep the `automatic_options` default to False.

I will keep this PR open for comment.

**Comment by ashleysommer** [comment]
Also regarding this PR,
I've noticed there is a _lot_ of formatting changes across the entire `core.py` file.
I'm not opposed to formatting changes, but they belong in a different Pull request.
This PR should be a single line change on line 54 only.

**Comment by fpischedda** [comment]
Hi Ashley,

I'd like to address the formatting issue because it is the easiest and we can move on on the more interesting stuff later; unfortunately I have not noticed that I have pushed those changes because a emacs plugin have done that under the hood, sorry :)

I understand the reasons behind your choice to keep automatic_options set to False but thinking about the most common use case (a RESTy API to be consumed probably by single page applications living in a different domain) it is highly probable that someone will always need to set this option to True.

I agree that this setting should be explicitly set but I'd like to do it only once per app or blueprint instead of per view; I'd like to help to add such a feature if we can agree on how to do it.

**Comment by ashleysommer** [comment]
To be honest I actually thought it was already possible to set `automatic_options` once per app as an application-wide option. I wrote out a full response to suggest you might have missed it, and to use that option, only to find that I was wrong and such an option doesn't exist at application level. When I wrote my response yesterday I was under the assumption that such does exist in Sanic-CORS.

When I wrote:
> By having `automatic_options` default to `False`, the user is choosing to 'opt-out' of the default behaviour by setting it to `True`, they are indicating that they want to change the way Sanic usually works.

I was implying that the user should be able to choose to 'opt-out' of the default behaviour at an application-level. I agree it is tedious to set this option on every route/view.

It is a simple change to make, and I can implement that option shortly.

**Comment by ashleysommer** [comment]
Ok, another update on this issue.
So it turns out there _*was*_ already two ways to set the `automatic_options` config on an application-level.

First there is this way:
```python
app = Sanic(__name__)
CORS(app, automatic_options=True)

@app.route('/test')
async def get_test(request):
    return text('hello world')
```
Using this method, this sets up standard CORS headers on ALL requests (you don't need to use `@cross_origin(app)` on your routes), and also applies the options in kwargs to all requests (in the case in this example it applies `automatic_options` to all requests).

Secondly, if you don't want to use the `CORS(app)` extension controller, (if you just want to use `@cross_origin(app)` decorator on specific routes), then you can use the `app.config` method:

```python
app = Sanic(__name__)
app.config['CORS_AUTOMATIC_OPTIONS'] = True

@app.route('/test', methods=["GET", "OPTIONS"])
@cross_origin(app)
async def get_test(request):
    return text('hello world')
```
Sanic-CORS has the ability to read any config variable stored in the `app.config` container, that has a key starting with `"CORS_"`. In this case, it sets `automatic_options` to true for all routes _including_ those using the `@cross_origin` decorator. Notice however you will need to add "OPTIONS" to the allowed methods passed to the Sanic `@app.route()` decorator to keep the Sanic router happy when using `automatic_options` in this manner.

Finally, this can `app.config` method also be used with the `CORS()` extension controller like so:
```python
app = Sanic(__name__)
app.config['CORS_AUTOMATIC_OPTIONS'] = True
CORS(app)
@app.route('/test')
async def get_test(request):
    return text('hello world')
```

Finally, I found a bug in the `get_cors_options()` function in Sanic-CORS, it was not finished being ported from Flask-CORS properly. That bug caused `app.config` options to be ignored in Sanic-CORS, so those last two examples above wouldn't work if you tried to use those snippets. I have released a new version v0.5.4.2 that fixes that.

**Comment by fpischedda** [comment]
Thank you for your help, I have missed the application level option; I'll update the sanic-cors dependency to include your latest changes.

**Pull request closed without merging**
